### ISSUE TITLE
Bunny rotates incorrectly in Euler Angle mode

### ISSUE THREAD

**Issue by norbinz** [adafruit/Adafruit_WebSerial_3DModelViewer#6]
Hello,
The Viewer's bunny correctly follows my sensor rotations in Quaternion mode, but rotates incorrectly/strangely in Euler Angles mode. Both modes should rotate identically. I don't know if the culprit is the Viewer or the Arduino sketch.

- Viewer URL https://adafruit.github.io/Adafruit_WebSerial_3DModelViewer/.
- My sensor is an Adafruit 3463 NXP 9-DOF.
- My Arduino sketch is Adafruit's "calibrated_orientation.ino" from library "Adafruit_AHRS" but with #include file changed to "NXP_FXOS_FXAS.h".
- My microcontroller is an Adafruit 2590 Metro Mini.
- My browser is Chrome Portable 99.0.4844.74, running in a sandbox, on Win7 64-bit, with NVidia GTX 1070 and driver 457.51.

I hope that's sufficient info!

**Comment by ladyada** [comment]
euler angles will not rotate the same near 180 degress, thats why there's two modes! :)

**Comment by ladyada** [comment]
if you can that would be great - from what we recall euler always has problems at the 0/180degree transitions
to run, you can fork and run it from github.io like we do, it is not hosted locally or on a server

**Comment by norbinz** [comment]
I will explore github.io  Thank you!

And congrats on creating and operating your business.

**Comment by norbinz** [comment]
Hi ladyada, here's my fix:

Near the bottom of script.js, replace this:

  if (bunny != undefined) {
    if (angleType.value == "euler") {
      bunny.rotation.x = THREE.Math.degToRad(360 - orientation[2]);
      bunny.rotation.y = THREE.Math.degToRad(orientation[0]);
      bunny.rotation.z = THREE.Math.degToRad(orientation[1]);
    } else {
      let rotObjectMatrix = new THREE.Matrix4();
      let rotationQuaternion = new THREE.Quaternion(quaternion[1], quaternion[3], -1 * quaternion[2], quaternion[0]);
      rotObjectMatrix.makeRotationFromQuaternion(rotationQuaternion);
      bunny.quaternion.setFromRotationMatrix(rotObjectMatrix);
    }
  }

with this:

  if (bunny != undefined) {
    if (angleType.value == "euler") {
      let rotationEuler = new THREE.Euler(THREE.Math.degToRad(orientation[2]), THREE.Math.degToRad(orientation[0]-180), THREE.Math.degToRad(-orientation[1]), 'YZX');
      bunny.setRotationFromEuler(rotationEuler);
    } else {
      let rotationQuaternion = new THREE.Quaternion(quaternion[1], quaternion[3], -quaternion[2], quaternion[0]);
      bunny.setRotationFromQuaternion(rotationQuaternion);
    }
  }

Quaternion and Euler modes now behave the same.
Notice the new 'YZX' rotation order - very important!
I also tried to tighten-up the code. I hope I coded it properly. I'm a javascript and three.js newbie.

**Comment by ladyada** [comment]
ok! @makermelissa will take a look when she has time!

**Comment by norbinz** [comment]
Success! The 3D Viewer bunny now moves correctly in both Quaternion and Euler modes with my NXP 9-DOF sensor (and probably other sensors too, except of course the BNO055 with its broken Euler math).

You may wish to revisit other Adafruit projects and documents that have incorrect Euler behavior, and check for incorrect rotation order or mixed-up axes.

**Comment by ladyada** [comment]
awesome thank you :)
